# Generated by Django 3.1 on 2020-08-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64, verbose_name='文档名')),
                ('file_title', models.CharField(max_length=64, verbose_name='文档标题')),
                ('file_content', models.CharField(max_length=128, verbose_name='文档内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='文档创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='文档最后一次修改时间')),
                ('permission', models.IntegerField(choices=[(1, '可查看'), (2, '可评论'), (3, '可修改'), (4, '可分享')], verbose_name='总权限')),
                ('team_permission', models.IntegerField(choices=[(1, '成员可查看'), (2, '成员可评论'), (3, '成员可修改'), (4, '成员可分享')], verbose_name='团队内部权限')),
                ('share', models.CharField(max_length=64, verbose_name='分享')),
                ('comments', models.ManyToManyField(through='myapp.Comment', to='myapp.User', verbose_name='评论')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfile', to='myapp.user', verbose_name='文档创建者')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file', verbose_name='被评论的文档'),
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='评论人'),
        ),
    ]
