# Generated by Django 3.1 on 2020-08-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200810_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='团队名称')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('team', '团队文档'), ('private', '私人文档')], default='private', max_length=32, verbose_name='文档类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfiles', to='myapp.user', verbose_name='文档创建者'),
        ),
        migrations.AlterField(
            model_name='file',
            name='share',
            field=models.CharField(max_length=64, null=True, verbose_name='分享'),
        ),
        migrations.AlterField(
            model_name='file',
            name='team_permission',
            field=models.IntegerField(choices=[(1, '成员可查看'), (2, '成员可评论'), (3, '成员可修改'), (4, '成员可分享')], null=True, verbose_name='团队内部权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='UserKeptFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kept_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file', verbose_name='收藏的文档')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='收藏的用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserBrowseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最近一次浏览时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file', verbose_name='浏览的文档')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='浏览的用户')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('permission', models.IntegerField(choices=[(1, '可查看'), (2, '可评论'), (3, '可修改'), (4, '可分享')], verbose_name='成员权限')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='团队成员')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team', verbose_name='所属团队')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_own', to='myapp.user', verbose_name='团队创建者'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='myapp.TeamMember', to='myapp.User', verbose_name='团队成员'),
        ),
        migrations.AddField(
            model_name='file',
            name='team_belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamfiles', to='myapp.team', verbose_name='所属团队'),
        ),
        migrations.AddField(
            model_name='user',
            name='browse',
            field=models.ManyToManyField(related_name='browse', through='myapp.UserBrowseFile', to='myapp.File', verbose_name='最近浏览'),
        ),
        migrations.AddField(
            model_name='user',
            name='kept',
            field=models.ManyToManyField(related_name='kept', through='myapp.UserKeptFile', to='myapp.File', verbose_name='收藏'),
        ),
    ]
