# Generated by Django 3.1 on 2020-08-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200810_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='team_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamfiles', to='myapp.team', verbose_name='所属团队'),
        ),
    ]
