# Generated by Django 3.1 on 2020-08-10 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200810_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='用户邮箱')),
                ('send_choice', models.CharField(max_length=20, verbose_name='发送类型')),
                ('send_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='发送时间')),
                ('exprie_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'emailrecord',
                'verbose_name_plural': 'emailrecord',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
