# Generated by Django 3.1 on 2020-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200810_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='modified_times',
            field=models.IntegerField(default=0, null=True, verbose_name='修改次数'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='permission',
            field=models.IntegerField(choices=[(1, '可查看'), (2, '可评论'), (3, '可修改'), (4, '可分享'), (5, 'all')], default=5, verbose_name='成员权限'),
        ),
    ]
