# Generated by Django 3.1 on 2020-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200811_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_title',
            field=models.CharField(default='无标题', max_length=64, verbose_name='文档标题'),
        ),
    ]
