# Generated by Django 3.1 on 2020-08-11 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200811_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='comments',
            field=models.ManyToManyField(related_name='comment_file', through='myapp.Comment', to='myapp.User', verbose_name='评论'),
        ),
        migrations.CreateModel(
            name='Modify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('modify_times', models.IntegerField(default=0, verbose_name='修改次数')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file', verbose_name='被修改的文档')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='修改的用户')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='modified_user',
            field=models.ManyToManyField(related_name='modified_name', through='myapp.Modify', to='myapp.User', verbose_name='文档修改人'),
        ),
    ]
