# Generated by Django 3.1 on 2020-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200811_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否在回收站'),
        ),
    ]
