# Generated by Django 3.1 on 2020-08-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200811_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.CharField(max_length=128, null=True, verbose_name='文档内容'),
        ),
    ]
