# Generated by Django 3.1 on 2020-08-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200811_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='file',
            name='team_permission',
        ),
        migrations.CreateModel(
            name='PrivilegeTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_permission', models.IntegerField(choices=[(1, '只能查看'), (2, '可评论和查看'), (3, '可编辑、评论和查看'), (4, '所有权限包括分享')], verbose_name='团队权限')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='权限修改时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file', verbose_name='文档')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='成员')),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegePri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(1, '只能查看'), (2, '可评论和查看'), (3, '可编辑、评论和查看'), (4, '所有权限包括分享')], verbose_name='权限')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='权限修改时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file', verbose_name='文档')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='dif_privilege',
            field=models.ManyToManyField(related_name='file_privilege_pri', through='myapp.PrivilegePri', to='myapp.User', verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='file',
            name='dif_team_privilege',
            field=models.ManyToManyField(related_name='file_privilege_team', through='myapp.PrivilegeTeam', to='myapp.User', verbose_name='团队权限'),
        ),
    ]
