# Generated by Django 3.1 on 2020-08-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200812_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='permission',
        ),
    ]
