# Generated by Django 3.1 on 2020-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200812_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='delete_time',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
    ]
