# Generated by Django 3.1 on 2020-08-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_file_is_edit_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('favor', '收藏'), ('comment', '评论'), ('team', '团队')], max_length=32, verbose_name='消息类型')),
                ('msg_title', models.CharField(max_length=128, verbose_name='消息头')),
                ('msg_content', models.TextField(verbose_name='消息内容')),
                ('msg_from', models.CharField(max_length=128, null=True, verbose_name='消息来源')),
                ('msg_time', models.DateTimeField(auto_now_add=True, verbose_name='消息时间')),
                ('msg_is_read', models.BooleanField(default=False, verbose_name='消息是否已读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_msg', to='myapp.user', verbose_name='用户')),
            ],
        ),
    ]
