# Generated by Django 3.1 on 2020-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_id', models.IntegerField(unique=True, verbose_name='模板唯一标识')),
                ('mod_content', models.TextField(verbose_name='模板内容')),
            ],
        ),
    ]
