# Generated by Django 3.1 on 2020-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg_from',
        ),
        migrations.AddField(
            model_name='message',
            name='msg_person_from',
            field=models.IntegerField(null=True, verbose_name='谁导致的这条消息'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type_from',
            field=models.IntegerField(null=True, verbose_name='文件或团队id'),
        ),
    ]
