# Generated by Django 3.1 on 2020-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_message_msg_is_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree',
            field=models.ManyToManyField(related_name='agree_user', to='myapp.Comment', verbose_name='点赞'),
        ),
        migrations.AddField(
            model_name='user',
            name='disagree',
            field=models.ManyToManyField(related_name='disagree_user', to='myapp.Comment', verbose_name='踩'),
        ),
    ]
