# Generated by Django 3.1 on 2020-08-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_message_msg_is_invite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-msg_time']},
        ),
        migrations.CreateModel(
            name='Disagree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disagree_time', models.DateTimeField(auto_now_add=True, verbose_name='踩时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comment', verbose_name='踩评论')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagrees', to='myapp.user', verbose_name='踩人')),
            ],
        ),
        migrations.CreateModel(
            name='Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comment', verbose_name='点赞评论')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrees', to='myapp.user', verbose_name='点赞人')),
            ],
        ),
    ]
