# Generated by Django 3.1 on 2020-08-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20200817_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disagree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disagree_time', models.DateTimeField(auto_now_add=True, verbose_name='踩时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comment', verbose_name='踩评论')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagrees', to='myapp.user', verbose_name='踩人')),
            ],
        ),
        migrations.CreateModel(
            name='Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comment', verbose_name='点赞评论')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrees', to='myapp.user', verbose_name='点赞人')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='agree',
            field=models.ManyToManyField(related_name='agree_user', through='myapp.Agree', to='myapp.Comment', verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disagree',
            field=models.ManyToManyField(related_name='disagree_user', through='myapp.Disagree', to='myapp.Comment', verbose_name='踩'),
        ),
    ]
