# Generated by Django 3.1 on 2020-08-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200817_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-msg_time']},
        ),
        migrations.AddField(
            model_name='message',
            name='msg_person_from_name',
            field=models.CharField(max_length=128, null=True, verbose_name='谁导致的这条消息'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type_from_name',
            field=models.CharField(max_length=128, null=True, verbose_name='文件或团队name'),
        ),
    ]
