# Generated by Django 3.1 on 2020-08-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20200817_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_is_accept',
            field=models.BooleanField(null=True, verbose_name='消息是否被接受'),
        ),
    ]
