# Generated by Django 3.1 on 2020-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_message_msg_is_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=128, null=True, verbose_name='头像url'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female')], null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=54, null=True, verbose_name='qq'),
        ),
    ]
