# Generated by Django 3.1 on 2020-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200818_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.CharField(max_length=128, null=True, verbose_name='团队头像url'),
        ),
    ]
