# Generated by Django 3.1 on 2020-08-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('favor', '收藏'), ('comment', '评论'), ('team', '团队'), ('share', '团队')], max_length=32, verbose_name='消息类型'),
        ),
    ]
